export const ADD_BUN = 'ADD_BUN';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const DELETE_INGREDIENTS = 'DELETE_INGREDIENTS';

export const UPDATE_CONSTRUCTOR_LIST = 'UPDATE_CONSTRUCTOR_LIST';

export const CALCULATE_TOTAL_PRICE = 'CALCULATE_TOTAL_PRICE';
